development:
  host: localhost
  database: get-those-titles_development
  port: 27017

test:
  host: localhost
  database: get-those-titles_test

# set these environment variables on your prod server
production:
  <% if ENV['MONGOLAB_URI'] %>
  <% uri = URI.parse(ENV['MONGOLAB_URI']) %>
  <% host = uri.host %>
  <% port = uri.port %>
  <% username = uri.user %>
  <% password = uri.password %>
  <% database = uri.path.gsub(/^\//, '') %>
  #uri: <%= ENV['MONGOLAB_URI'] %>
  host: <%= host %>
  port: <%= port %>
  username: <%= username %> 
  password: <%= password %> 
  database: <%= database %> 
  
  <% end %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
